---
title: "Lab 01 - Hello R"
author: "Steph Bossert"
date: "4 Feb 21"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```
## Exercises

### Exercise 1

```{r}
datasaurus_dozen %>%
  count(dataset) %>%
  print(13)
```
1) 13 rows and 2 columns 

### Exercise 2
First let's plot the data in the dino dataset:

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```
Correlation = -.065
### Exercise 3

```{r plot-star, fig.height=3, fig.width=6}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()

star_data %>%
  summarize(r = cor(x, y))
```
Correlation = -0.0630 

### Exercise 4
```{r plot-circle, fig.height=3, fig.width=6}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()

circle_data %>%
  summarize(r = cor(x, y))
```

```

### Exercise 5
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
  
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)
```{r}
```


```{r}
```
  
  

